[build]
  base = "client"
  publish = "dist"
  command = "npm ci && npm run build"

[build.environment]
  VITE_API_BASE = "https://kidgame1backend.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200